<a href="https://colab.research.google.com/github/SimmyKumari12/Capgemini-Session-DailyCodes/blob/main/Day5Capgemini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [ ]:
df = pd.read_csv("/content/SalesData.csv")
df

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...
249,10709,28-12-2022,Sides & Other,4.99,200.40,Drive-thru,Gift Card,Walter Muller,Berlin
250,10710,29-12-2022,Burgers,12.99,754.43,Drive-thru,Gift Card,Walter Muller,Berlin
251,10711,29-12-2022,Chicken Sandwiches,9.95,281.41,Drive-thru,Gift Card,Walter Muller,Berlin
252,10712,29-12-2022,Fries,3.49,630.37,Drive-thru,Gift Card,Walter Muller,Berlin
253,10713,29-12-2022,Beverages,2.95,677.97,Drive-thru,Gift Card,Walter Muller,Berlin

In [ ]:
df.shape

(254, 9)

In [ ]:
df.dtypes

Order ID            int64
Date               object
Product            object
Price             float64
Quantity          float64
Purchase Type      object
Payment Method     object
Manager            object
City               object
dtype: object

In [ ]:
df.isnull().sum()

Order ID          0
Date              0
Product           0
Price             0
Quantity          0
Purchase Type     0
Payment Method    0
Manager           0
City              0
dtype: int64

In [ ]:
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [Order ID, Date, Product, Price, Quantity, Purchase Type, Payment Method, Manager, City]
Index: []

In [ ]:
df.Quantity = df["Quantity"].astype(int)

In [ ]:
df.Date = pd.to_datetime(df.Date,format="mixed")

In [ ]:
df.Date.dt.month

0       7
1       7
2       7
3       8
4       8
       ..
249    12
250    12
251    12
252    12
253    12
Name: Date, Length: 254, dtype: int32

In [ ]:
df.Date.head()

0   2022-07-11
1   2022-07-11
2   2022-07-11
3   2022-08-11
4   2022-08-11
Name: Date, dtype: datetime64[ns]

#### Most preferred Payment method

In [ ]:
df

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-07-11,Fries,3.49,573,Online,Gift Card,Tom Jackson,London
1,10453,2022-07-11,Beverages,2.95,745,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-07-11,Sides & Other,4.99,200,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-08-11,Burgers,12.99,569,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-08-11,Chicken Sandwiches,9.95,201,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...
249,10709,2022-12-28,Sides & Other,4.99,200,Drive-thru,Gift Card,Walter Muller,Berlin
250,10710,2022-12-29,Burgers,12.99,754,Drive-thru,Gift Card,Walter Muller,Berlin
251,10711,2022-12-29,Chicken Sandwiches,9.95,281,Drive-thru,Gift Card,Walter Muller,Berlin
252,10712,2022-12-29,Fries,3.49,630,Drive-thru,Gift Card,Walter Muller,Berlin
253,10713,2022-12-29,Beverages,2.95,677,Drive-thru,Gift Card,Walter Muller,Berlin

In [ ]:
df["Payment Method"].value_counts()

Payment Method
Credit Card    120
Cash            76
Gift Card       58
Name: count, dtype: int64

In [ ]:
df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

Product
Beverages             34938
Fries                 32016
Burgers               28996
Chicken Sandwiches    11132
Sides & Other          9800
Name: Quantity, dtype: int64

In [ ]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [ ]:
df

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Revenue
0,10452,2022-07-11,Fries,3.49,573,Online,Gift Card,Tom Jackson,London,1999.77
1,10453,2022-07-11,Beverages,2.95,745,Online,Gift Card,Pablo Perez,Madrid,2197.75
2,10454,2022-07-11,Sides & Other,4.99,200,In-store,Gift Card,Joao Silva,Lisbon,998.00
3,10455,2022-08-11,Burgers,12.99,569,In-store,Credit Card,Walter Muller,Berlin,7391.31
4,10456,2022-08-11,Chicken Sandwiches,9.95,201,In-store,Credit Card,Walter Muller,Berlin,1999.95
...,...,...,...,...,...,...,...,...,...,...
249,10709,2022-12-28,Sides & Other,4.99,200,Drive-thru,Gift Card,Walter Muller,Berlin,998.00
250,10710,2022-12-29,Burgers,12.99,754,Drive-thru,Gift Card,Walter Muller,Berlin,9794.46
251,10711,2022-12-29,Chicken Sandwiches,9.95,281,Drive-thru,Gift Card,Walter Muller,Berlin,2795.95
252,10712,2022-12-29,Fries,3.49,630,Drive-thru,Gift Card,Walter Muller,Berlin,2198.70
253,10713,2022-12-29,Beverages,2.95,677,Drive-thru,Gift Card,Walter Muller,Berlin,1997.15

In [ ]:
df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)

Product
Burgers               376658.04
Fries                 125602.14
Chicken Sandwiches    114602.50
Beverages             103067.10
Sides & Other          48902.00
Name: Revenue, dtype: float64

#### Which city had maximum revenue
OR
#### Which manager earned maximum revenue

In [ ]:
df.groupby("City")["Revenue"].sum().sort_values(ascending=False)

City
Lisbon    241509.38
London    211001.83
Madrid    136098.22
Berlin    100492.73
Paris      79729.62
Name: Revenue, dtype: float64

In [ ]:
df.groupby("Manager")["Revenue"].sum().sort_values(ascending=False)

Manager
Joao Silva            224883.41
Tom Jackson           209002.06
Pablo Perez           107522.59
Walter Muller         100492.73
Remy Monet             72734.93
       Pablo Perez     23180.23
Joao    Silva          16625.97
       Remy Monet       3996.92
Pablo  Perez            2198.70
Pablo   Perez           2198.70
Tom      Jackson        1999.77
Remy    Monet           1999.77
Pablo    Perez           998.00
Remy     Monet           998.00
Name: Revenue, dtype: float64

#### Average Revenue Of November and December

In [ ]:
df[df["Date"].dt.month == 11]["Revenue"].mean()

np.float64(2967.8207216494843)

In [ ]:
df[df["Date"].dt.month == 12]["Revenue"].mean()

np.float64(3192.758191489363)

#### Compare revenue by purchase type

In [ ]:
val = df.groupby("Purchase Type")["Revenue"].sum().sort_values(ascending=False).reset_index

In [ ]:
sns.barplot(x="Purchase Type",y = "Revenue", data = val).sum().values
plt.show()

TypeError: Data source must be a DataFrame or Mapping, not <class 'method'>.